import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./providers";
import { MapStoreProvider } from "@/providers/MapStoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MapStoreProvider>
          <p className="alfa-slab-one-regular text-center my-5 text-3xl">
            Countries Grid
          </p>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </MapStoreProvider>
      </body>
    </html>
  );
}
